22-authentication-authorization/config/routes.rb
Rails.application.routes.draw do
  resource :users
  resources :students, only: [:show, :new, :index, :create]
  root 'students#index'

  get '/register', to: "users#new", as: "register_path"
  post '/register', to: "users#create"

  get '/login', to: "auth#login", as: "login_path"
  post '/login', to: "auth#verify"
  get '/logout', to: "auth#logout", as: "logout"
end

22-authentication-authorization/app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students
end

22-authentication-authorization/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort, optional: true

  validates :name, :email, presence: true
  validates :email, uniqueness: true
end

22-authentication-authorization/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # def password=(password)
  #   Digest::SHA256.base64digest(password)
  # end
  #
  # def validates(password)
  #   self.password == password
  # end

  # login :
  #   if the password matches,
  #   take them to the index
  #   else render the login form again
end

22-authentication-authorization/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :redirect_user, :logged_in?

  def redirect_user
    if !logged_in?
      redirect_to login_path
    end
  end

  def logged_in?
    !!session[:user_id]
  end

end

22-authentication-authorization/app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
    # @logged_in = logged_in?
  end

  def verify
    # byebug
    @user = User.find_by(username: params[:auth][:username])
    if @user && @user.authenticate(params[:auth][:password])
      # session[:username]
      session[:user_id] = @user.id
      redirect_to students_path
    else
      render :login
    end
  end

  def logout
    session.clear
    redirect_to login_path
  end

end

22-authentication-authorization/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :redirect_user

  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render :new
    end

  end

  private
  def student_params
    params.require(:student).permit(:name, :email, :cohort_id)
  end
end

22-authentication-authorization/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    byebug
    @user = User.new(username:params[:user][:username], password: params[:user][:password])
    if @user.save
      redirect_to students_path
    else
      flash[:message] = "Please enter the correct stuff"
      render :new
    end

  end

end

22-authentication-authorization/app/helpers/students_helper.rb
module StudentsHelper
end

22-authentication-authorization/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
  </head>
  <div class="ui teal inverted menu">
    <a href="/" class="item">
      <h1>Student Lister</h1>
    </a>
    <% if logged_in? %>
      <div class="right menu">
        <%= link_to 'Logout', logout_path, {class: 'item'} %>
        <%= link_to 'Create a New Student', new_student_path, {class: 'item'} %>
      </div>
    <% end %>
  </div>
  <body>
    <div class="ui centered grid ">
      <div class="eight wide column">

        <%= yield %>

      </div>
    </div>
  </body>
</html>

22-authentication-authorization/app/views/students/index.html.erb
<h1>All Students</h1>

<div class= 'ui huge middle aligned selection divided list'>
  <% @students.each do |student| %>
    <div class="item">
      <%= link_to student.name, student_path(student) %>
    </div>
  <% end %>
</div>

22-authentication-authorization/app/views/students/new.html.erb
<h1>Create a Student</h1>

<%= form_for @student, html: {class: 'ui form'} do |f| %>
  <div class="field">
    <%= f.text_field(:name, placeholder: 'Enter the student name...') %>
  </div>
  <div class="field">
    <%= f.text_field :email, placeholder: 'Enter the student email...' %>
  </div>
  <div class="field">
    <%= f.collection_select(:cohort_id, Cohort.all, :id, :name) %>
  </div>
  <%= f.submit({class: 'ui huge pink button'}) %>
<% end %>

22-authentication-authorization/app/views/students/show.html.erb
<div class='ui raised segment'>
  <div class='ui fluid card'>
    <div class='huge content'>
      <div class='header'><h1><%= @student.name %></h1></div>
      <div class="meta">
         <span class="date">
           <h3><%= @student.cohort.name %> (<%= @student.cohort.start_date.strftime('%m%d%y') %>)</h3>
         </span>
      </div>
      <div class="description">
        <h3><%= @student.email %></h3>
      </div>
    </div>
  </div>
</div>

22-authentication-authorization/app/views/users/new.erb
<%= flash[:message] %>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit %>
<% end %>