20-rails-review/brews-crew/config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  get 'brews/strongest', to: 'brews#strongest'
  resources :brews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

20-rails-review/brews-crew/app/models/brew.rb
class Brew < ApplicationRecord
    has_many :purchases
    validates :blend_name, uniqueness: :true
    
    def self.strongest
        strongest_strength = Brew.first.strength
        Brew.all.each do |brew|
            if brew.strength > strongest_strength
                strongest_strength = brew.strength
            end
        end
        Brew.all.select do |brew|
             brew.strength == strongest_strength
        end
    end
end

20-rails-review/brews-crew/app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :brew
    validates :size, inclusion: {in: %w(small medium large)}
    validates :creamer_strength, inclusion: {in: %w(light regular none)}
    validates :special_instructions, length: {maximum: 140}
end

20-rails-review/brews-crew/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

20-rails-review/brews-crew/app/controllers/brews_controller.rb
class BrewsController < ApplicationController
    
    def index
        @brews = Brew.all

    end

    def new
        @brew = Brew.new
    end

    def create
        @brew = Brew.create(brews_params)
        redirect_to @brew
    end

    def edit
        @brew = Brew.find(params[:id])
    end

    def update
        @brew = Brew.find(params[:id])
        @brew.update(brews_params)
        redirect_to @brew
    end

    def show
        @brew = Brew.find(params[:id])
    end 

    def destroy
        @brew = Brew.find(params[:id])
        @brew.delete
        redirect_to brews_path
    end

    def strongest
       @strongest_blends = Brew.strongest
    end

    private

    def brews_params
        params.require(:brew).permit(:blend_name, :origin, :notes, :strength)
    end
end

20-rails-review/brews-crew/app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    def new
        @purchase = Purchase.new
        @brews = Brew.all
    end

    def create
        @brews = Brew.all
        @purchase = Purchase.new(purchase_params)
        byebug
        if @purchase.save
            redirect_to purchase_path(@purchase)
        else 
            render :new
        end
    end

    def show
        @purchase = Purchase.find(params[:id])
    end

    def index
        @purchases = Purchase.all
    end

    private

    def purchase_params
        params.require(:purchase).permit(:customer_name, :price, :brew_id, :size, :creamer_strength, :special_instructions)
    end
end

20-rails-review/brews-crew/app/helpers/brews_helper.rb
module BrewsHelper
end

20-rails-review/brews-crew/app/helpers/purchases_helper.rb
module PurchasesHelper
end

20-rails-review/brews-crew/app/views/brews/edit.html.erb
<%= form_for @brew do |f|%>
<%= f.label :blend_name%>
<%= f.text_field :blend_name%>
<%= f.label :origin%>
<%= f.text_field :origin%>
<%= f.label :notes%>
<%= f.text_field :notes%>
<%= f.label :strength %>
<%= f.number_field :strength%>
<%= f.submit%>
<%end%>

20-rails-review/brews-crew/app/views/brews/index.html.erb
<% @brews.each do |brew|%>
<%= link_to brew.blend_name, brew_path(brew)%>
<%=link_to "delete", brew, method: :delete %>

<%end%>

20-rails-review/brews-crew/app/views/brews/new.html.erb
<%= form_for @brew do |f|%>
<%= f.label :blend_name%>
<%= f.text_field :blend_name%>
<%= f.label :origin%>
<%= f.text_field :origin%>
<%= f.label :notes%>
<%= f.text_field :notes%>
<%= f.label :strength %>
<%= f.number_field :strength%>
<%= f.submit%>
<%end%>

20-rails-review/brews-crew/app/views/brews/show.html.erb
<%= @brew.blend_name%>
<%= @brew.origin%>
<%= @brew.notes%>
<%= @brew.strength%>

<% @brew.purchases.each do |purchase|%>
<%= purchase.customer_name%>
<%end%>

20-rails-review/brews-crew/app/views/brews/strongest.html.erb
<% @strongest_blends.each do |blend|%>
<%= blend.blend_name %>
<%end%>

20-rails-review/brews-crew/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrewsCrew</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

20-rails-review/brews-crew/app/views/purchases/index.html.erb
<ul>

<% @purchases.each do |purchase|%>
<li><%= purchase.customer_name%>
<%= purchase.price%>
<%= link_to purchase.brew.blend_name, purchase_path(purchase)  %></li>
<%end%>
</ul>

20-rails-review/brews-crew/app/views/purchases/new.html.erb
<%= form_for @purchase do |f|%>
<%= f.label :customer_name%>
<%= f.text_field :customer_name %>
<%= f.label :price%>
<%= f.number_field :price %>
<%= f.label :selected_brew%>
<%= f.collection_select :brew_id, @brews, :id, :blend_name %>
<%= f.label :size%>
<%= f.text_field :size%>
<%= f.label :creamer_strength%>
<%= f.text_field :creamer_strength%>
<%= f.label :special_instructions%>
<%= f.text_field :special_instructions%>
<%= f.submit%>
<%end%>

20-rails-review/brews-crew/app/views/purchases/show.html.erb
<%= @purchase.customer_name%>
<%= @purchase.price %>
<%= link_to @purchase.brew.blend_name, brew_path(@purchase.brew)%>
<%= @purchase.size %>
<%= @purchase.creamer_strength%>
<%= @purchase.special_instructions%>